### ISSUE TITLE
Unit tests never actually verify the fields of the parsed PackageURL

### ISSUE THREAD

**Issue by petergardfjall** [package-url/packageurl-go#14]
At the moment, the `TestFromStringExamples` [1] parsing unit test does little else than verify that the parsing completes without an error. For each parsed purl, the purl's struct fields should be compared against the expected field values of the `TestFixture`.

[1] https://github.com/package-url/packageurl-go/blob/79c5c528709b44258fefa345d2cd9930c523c005/packageurl_test.go#L48-L77

I have code that solves this but it relies on PR #13 being merged. Let me know if you need help on this.

**Comment by ashcrow** [comment]
#13 has now merged. If you still have the code around post it up and I'm happy to merge it in!

**Comment by petergardfjall** [comment]
See https://github.com/package-url/packageurl-go/pull/16

**Comment by ashcrow** [comment]
https://github.com/package-url/packageurl-go/pull/16 merged.
