### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by ashcrow** [package-url/packageurl-go#15]
Right now we are not doing releases of `packageurl-go`. We should. Cut a release once the current set of issues have been run through and travis is passing.

**Comment by petergardfjall** [comment]
I think we are fairly close to this after https://github.com/package-url/packageurl-go/pull/16.
I'm not sure if you're have merge rights in the https://github.com/package-url/purl-spec repo, but as mentioned in the pull request, we need https://github.com/package-url/purl-spec/pull/61 merged before all tests will pass.

**Comment by fitzoh** [comment]
Any updates now that #16 is complete?

**Comment by ashcrow** [comment]
:tada: https://github.com/package-url/packageurl-go/releases/tag/0.1.0

**Comment by petergardfjall** [comment]
@ashcrow Great news, _however_, in order for the release to play well with the Go module system, it needs to be prefixed by a `v`. So please change the tag from `0.1.0` to `v.0.1.0`.

**Comment by ashcrow** [comment]
Updated https://github.com/package-url/packageurl-go/releases/tag/v0.1.0

**Comment by petergardfjall** [comment]
@ashcrow Thanks, I've verified that it works with Go modules. :tada:
