### ISSUE TITLE
License detection issue

### ISSUE THREAD

**Issue by roycyt** [package-url/packageurl-go#20]
Hi,
I just found that the license of this package is not correctly detected by pkg.go.dev and GitHub.
It would be great to follow the convention(?) to rename the `mit.LICENSE` file to `LICENSE`.

Ref: https://pkg.go.dev/license-policy
Ref: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

**Comment by wagoodman** [comment]
This also causes havoc with automatic license audit tools, such as https://github.com/google/go-licenses . Moving the license to `LICENSE` would solve this.

**Comment by ashcrow** [comment]
In https://github.com/package-url/packageurl-go/pull/28 [LICENSE](https://github.com/package-url/packageurl-go/blob/master/LICENSE) now exists and `mit.LICENSE` is now a symlink to `LICENSE`.
