### ISSUE TITLE
godoc: Documentation not displayed due to license restrictions.

### ISSUE THREAD

**Issue by imjasonh** [package-url/packageurl-go#33]
Trying to view Go package doc in https://pkg.go.dev/github.com/package-url/packageurl-go shows the message:

> Documentation not displayed due to license restrictions.
> See our [license policy](https://pkg.go.dev/license-policy).

<img width="473" alt="Screen Shot 2022-07-05 at 3 36 30 PM" src="https://user-images.githubusercontent.com/210737/177402575-04af0011-7cf0-418a-831e-e09e05f5fc51.png">

Does anybody know what license issue they might be referring to? The repo is licensed under MIT, but maybe the [`mit.LICENSE` symlink](https://github.com/package-url/packageurl-go/blob/master/mit.LICENSE) is causing `pkg.go.dev` to get confused?

**Comment by shibumi** [comment]
Hi @imjasonh, I will have a look at this. Maybe the newest release v0.1.1 fixed the issue.
