### ISSUE TITLE
Please create a new release with the test data

### ISSUE THREAD

**Issue by andrewpollock** [package-url/packageurl-go#42]
Hello,

@another-rex and I are attempting to package packageurl-go for Debian as we need it for a build dependency.

The Debian packaging tooling is grabbing the v0.1.0 tagged release, which does not include the subsequent addition of the testdata (added most recently in ab67608befffc606e03a3d23772deb3eb4fec71d) so the package build fails.

Could you please make a new release that includes ab67608befffc606e03a3d23772deb3eb4fec71d?

Thanks

Andrew

**Comment by andrewpollock** [comment]
Thank you!

**Comment by andrewpollock** [comment]
To be super explicit:

A new `v0.1.1` release that includes https://github.com/package-url/packageurl-go/commit/ab67608befffc606e03a3d23772deb3eb4fec71d would satisfy this request

**Comment by shibumi** [comment]
Hey @pombredanne  @stevespringett can we get a tag + release?

**Comment by shibumi** [comment]
Hi @andrewpollock  I have created a new release that points to the latest commit on master. I hope this satisfies your issue.

If not, feel free to re-open or reach out to me as usually.
