### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by shibumi** [package-url/packageurl-go#45]
Hi @sschuberth  @stevespringett  @pombredanne @iamwillbar is this project still alive? 

If you are looking for a new co-maintainer, I would be willing to contribute. I think I am mentioned as one of the recent top contributors anyway and people start thinking that I am involved in the project 🤣

**Comment by sschuberth** [comment]
I'm not a Go person, so I'd be fine with you helping out as a maintainer! Do others agree?

**Comment by sschuberth** [comment]
> tag a new version

I've newer made releases from this repo (and CI / tests seem to be somewhat broken), so I'm probably not in a position to do that, unfortunately.

**Comment by shibumi** [comment]
@sschuberth no issue :) Do you have a different channel to reach out to @pombredanne  or @stevespringett ? I tried contacting both a few days ago, but there seems to be no answer yet. Would be really cool if we could speed up the process a little bit.

**Comment by sschuberth** [comment]
> Do you have a different channel to reach out to @pombredanne or @stevespringett ?

I have, but they usually react quickly to GitHub-mentions. Let's give them a few more days, maybe they're on travel or so.

**Comment by stevespringett** [comment]
Thanks for the contributions and willingness to step up as a maintainer @shibumi. Truly appreciate it. I personally am fine with promoting to maintainer, but like @sschuberth I am not a Go developer, so will not be able to assist with releases.

**Comment by shibumi** [comment]
Thank you, for your quick answer @sschuberth. That's fine for me. :)

I am already familiar with package-url and contribute to the supply chain security community. In the worst case, I know a few heavy packageurl-go users i can reach out to.

**Comment by sschuberth** [comment]
> Thank you, for your quick answer @sschuberth. That's fine for me. :)

@shibumi I've added you to this repo with the "Maintain" role.
