### ISSUE TITLE
PackageURL should implement the Stringer interface

### ISSUE THREAD

**Issue by petergardfjall** [package-url/packageurl-go#6]
At the moment, the PackageURL type provides a `ToString` method to output a textual representation of the package URL. 

A more idiomatic approach would be to implement the [Stringer interface](https://golang.org/pkg/fmt/#Stringer).

To not break backwards compatability, `String` should be implemented as a forwarding call to `ToString`.

**Comment by petergardfjall** [comment]
https://github.com/package-url/packageurl-go/pull/13 offers a fix.

**Comment by ashcrow** [comment]
#13 merged.
