### ISSUE TITLE
[bug] ./ and ../ are not valid subpath prefix

### ISSUE THREAD

**Issue by ridhoq** [package-url/packageurl-go#67]
A bug was discovered after upgrading to `v0.1.2` where `./` and `../` are not valid prefixes as seen here: https://github.com/guacsec/guac/issues/1545. It appears to be due to [this logic](https://github.com/package-url/packageurl-go/blob/master/packageurl.go#L461):

```go
if s == "." || s == ".." {
	return fmt.Errorf("invalid Package URL subpath: %q", p.Subpath)
}
```
As per the [SPDX spec](https://spdx.github.io/spdx-spec/v2.3/file-information/), file paths are generally prefixed with `./`. If a `purl` was to be constructed using the files read in from an SPDX SBOM, it would throw an error.

**Comment by lumjjb** [comment]
we are still running into some of these issues where `./` and `../` carry some meaning with the PURLs that are generated that include them... I do realize this is a bit more of an involved discussion, and wondering if @pombredanne and other PURL maintainers would be amicable to relax this requirement in the code only for now?

**Comment by lumjjb** [comment]
Yea agreed about the "../" values not making semantic sense for now.. i'm wondering if we can provide a build flag or alternate function that will parse legacy documents while things get eventually fixed? It is likely we'll still see a lot of these "bad PURLs" around for the near future?

**Comment by pombredanne** [comment]
@lumjjb it could make sense to publish a simple doc with fixes to apply to well known problematic inputs.
