### ISSUE TITLE
packageurl.FromString() fails to parse subpaths

### ISSUE THREAD

**Issue by petergardfjall** [package-url/packageurl-go#9]
The `packageurl.FromString()` function does not properly parse subpaths. It strips the result of slashes. The following code:
```
package main

import (
	"fmt"

	packageurl "github.com/package-url/packageurl-go"
)

func main() {
	p, _ := packageurl.FromString("pkg:golang/google.golang.org/genproto#googleapis/api/annotations")
	fmt.Printf("subpath: %v\n", p.Subpath)
}
```

results in
```
subpath: googleapisapiannotations
```

Note that the example purl is taken from the [purl-spec repo](https://github.com/package-url/purl-spec).

**Comment by petergardfjall** [comment]
https://github.com/package-url/packageurl-go/pull/16 offers a solution

**Comment by ashcrow** [comment]
https://github.com/package-url/packageurl-go/pull/16 merged.
